VIA_ENABLE = yes

VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

# Firmware Optimization
LTO_ENABLE = yes
QMK_SETTINGS = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
